routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {

	/**
	 * Rotas básicas do sistema
	 */
	
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('/setores', 'SetorController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);
	Route::resource('/responsaveis', 'ResponsavelController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);
	Route::resource('/cargos', 'CargoController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);
	Route::resource('/materiais', 'MaterialController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);

	/**
	 * Rotas para Ajax
	 */
	
	Route::get('/materiais/servidores-setor/', 'MaterialController@AjaxServidoresPorSetor')->name('ajax.servidores.por.setor');
	
});

app/Models/Cargo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cargo extends Model
{
	protected $table = 'cargos';

    protected $fillable =[
    	'nome',
    	'descricao',
    ];

    public function responsaveis()
    {
        return $this->hasMany('App\Models\Responsavel');
    }

    /**
     * Setando o atributo nome para uppercase
     * @param string $value
     * @return null
     */
    public function setNomeAttribute($value) 
    {
        $this->attributes['nome'] = mb_strtoupper($value);
    }
}

app/Http/Controllers/CargoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cargo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CargoController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cargos = Cargo::orderBy('nome', 'asc')->get();
        return view('sistema.cargos.index', compact('cargos'));
    }

    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'nome' => 'required|unique:cargos|max:255',
        ]);

        $cargo = Cargo::create($request->all());

        if ($cargo) {
            Session::flash('status', 'success');
            Session::flash('message', 'Cargo cadastrado com sucesso');

            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Cargo::find($id)->update($request->all())) {
            Session::flash('status', 'info');
            Session::flash('message', 'Cargo atualizado.');
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Cargo::find($id)->responsaveis->isNotEmpty()) {
            Session::flash('status', 'danger');
            Session::flash('message', 'ERRO: Não foi possível excluir. Servidores cadastrados nesse cargo.');

            return redirect()->back();
        }

        Cargo::destroy($id);
        return redirect()->back();

        
    }
}

resources/views/sistema/cargos/index.blade.php
@extends('adminlte::page')


@section('content_header')
	<h1>
    	Cargos <small>Visão Geral</small>
    </h1>


    <ol class="breadcrumb">
    	<li>
    		<i class="fa fa-home"></i>
    		<a href="{{ route('home') }}">Home</a>
    	</li>
    	<li class="active">
    		<i class="fa fa-briefcase"></i> Cargos
    	</li>
    </ol>
@stop

@section('content')

	@if(session('message'))
		<div class="alert alert-{{ session('status') }}" data-dismiss="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times</span>
			</button>
		    {{ session('message') }}
		</div>
	@endif

	<div class="row">

		<div class="col-lg-4 col-md-5">
			<div class="box  {{ ($errors->isNotEmpty()) ? 'box-danger' : '' }}">
				<div class="box-header">
					<h1 class="box-title">
						<i class="fa fa-plus"></i> Cadastrar Cargo
					</h1>
				</div>
				<div class="box-body">
								
					<form action="{{ route('cargos.store') }}" method="POST">

						{{ csrf_field() }}

						<div class="form-group {{ $errors->has('nome') ? 'has-error' : '' }}">
							<label for="nome">Nome: </label>
							<input type="text" name="nome" class="form-control" id="nome" autofocus value="{{ old('nome') }}">
							@if($errors->has('nome'))
								<span class="help-block">{{ $errors->first('nome') }}</span>
							@endif
						</div>

						<div class="form-group">
							<label for="descricao">Descrição:</label>
							<input type="text" name="descricao" class="form-control" id="descricao" {{ old('descricao') }}>
							<span class="help-block"><span class="label label-default">* Opcional</span></span>
						</div>
						
						<div class="form-group text-right">
							<button type="submit" class="btn btn-primary">
								Cadastrar
							</button>
						</div>

					</form>
				</div>
			</div>
		</div>

		<div class="col-lg-8 col-md-7">
				<div class="box box-default ">
					<div class="box-header ">
						<h1 class="box-title">
							<i class="fa fa-list"></i> Lista de Cargos
						</h1>
					</div>
					<div class="box-body">
						
						<div class="table-responsive">
							<table class="table table-hover table-condensed">
								<thead>
									<tr>
										<th>Nome</th>	
										<th>Ações</th>	
									</tr>
								</thead>
								<tbody>
									@foreach($cargos as $cargo)
									<tr>
										<td>{{ $cargo->nome }}</td>
										<td>
											<button type="button" class="btn btn-sm btn-default" data-toggle="modal"  title="Editar" data-target="#edit-modal-{{ $cargo->id }}">
											<i class="fa fa-edit"></i>
										</button>
										@component('components.form-editar.editar')
											@slot('item', $cargo)
											@slot('route', route('cargos.update', $cargo->id))
										@endcomponent

										<button class="btn btn-sm btn-detail btn-danger" title="Excluir" data-toggle='modal' data-target='#delete-modal-{{ $cargo->id }}'>
											<i class="fa fa-trash"></i>
										</button>
										@component('components.deletar')
											@slot('item', $cargo)
											@slot('route', route('cargos.destroy', $cargo->id))
										@endcomponent
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>

						</div>
					</div>
				</div>
		</div>
		
		{{-- @component('components.create')
			@slot('header', 'Cadastrar Cargo')
			@slot('route', route('cargos.store')) 
		@endcomponent

		@component('components.table')
			@slot('cabecalho', ' Lista de Cargos')
			@slot('titulos', ['Nome', 'Descrição', 'Ações'])
			@slot('items', $cargos)
		@endcomponent --}}
	</div>
	

@stop