routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {

	/**
	 * Rotas básicas do sistema
	 */
	
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('/setores', 'SetorController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);
	Route::resource('/responsaveis', 'ResponsavelController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);
	Route::resource('/cargos', 'CargoController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);
	Route::resource('/materiais', 'MaterialController', ['only' => ['index', 'show' ,'store', 'update', 'destroy']]);

	/**
	 * Rotas para Ajax
	 */
	
	Route::get('/materiais/servidores-setor/', 'MaterialController@AjaxServidoresPorSetor')->name('ajax.servidores.por.setor');
	
});

resources/views/sistema/setores/index.blade.php
@extends('adminlte::page')


@section('content_header')
    <h1>
    	Setores <small>Visão Geral</small>
    </h1>


    <ol class="breadcrumb">
    	<li>
    		<i class="fa fa-home"></i>
    		<a href="{{ route('home') }}">Home</a>
    	</li>
    	<li class="active">
    		<i class="fa fa-building"></i> Setores
    	</li>
    </ol>
@stop

@section('content')

    @if(session('message'))
		<div class="alert alert-{{ session('status') }}" data-dismiss="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times</span>
			</button>
		    {{ session('message') }}
		</div>
	@endif

	<div class="row">
		
		<div class="col-lg-4 col-md-5">
			<div class="box {{ ($errors->isNotEmpty()) ? 'box-danger' : '' }}">
				<div class="box-header">
					<h1 class="box-title">
						<i class="fa fa-plus"></i> Cadastrar Setor
					</h1>
				</div>
				<div class="box-body">
								
					<form action="{{ route('setores.store') }}" method="POST">

						{{ csrf_field() }}

						<div class="form-group {{ $errors->has('nome') ? 'has-error' : '' }}">
							<label for="nome">Nome: </label>
							<input type="text" name="nome" class="form-control" id="nome" autofocus value="{{ old('nome') }}">
							@if($errors->has('nome'))
								<span class="help-block">{{ $errors->first('nome') }}</span>
							@endif
						</div>

						<div class="form-group">
							<label for="descricao">Descrição:</label>
							<input type="text" name="descricao" class="form-control" id="descricao" {{ old('descricao') }}>
							<span class="help-block"><span class="label label-default">* Opcional</span></span>
						</div>
						
						<div class="form-group text-right">
							<button type="submit" class="btn btn-primary">
								Cadastrar
							</button>
						</div>

					</form>
				</div>
			</div>
		</div>
		<div class="col-lg-8 col-md-7">
			<div class="box box-default">
				<div class="box-header ">
					<h1 class="box-title">
						<i class="fa fa-list"></i> Lista de Setores	 
					</h1>
				</div>
				<div class="box-body">
					
					<div class="table-responsive">
						<table class="table table-hover table-condensed">
							<thead>
								<tr>
									<th>Nome</th>	
									<th>Ações</th>		
								</tr>
							</thead>
							<tbody>
								@foreach($setores as $setor)
								<tr>
									<td>{{ $setor->nome }}</td>
									<td>
										<a href="{{ route('setores.show', $setor->id) }}" class="btn btn-sm btn-default">
											<i class="fa fa-cubes"></i> Materiais
										</a>
									

										<button type="button" class="btn btn-sm btn-default" data-toggle="modal"  title="Editar" data-target="#edit-modal-{{ $setor->id }}">
											<i class="fa fa-edit"></i>
										</button>
										@component('components.form-editar.editar')
											@slot('item', $setor)
											@slot('route', route('setores.update', $setor->id))
										@endcomponent

										<button class="btn btn-sm btn-detail btn-danger" title="Excluir" data-toggle='modal' data-target='#delete-modal-{{ $setor->id }}'>
											<i class="fa fa-trash"></i>
										</button>
										@component('components.deletar')
											@slot('item', $setor)
											@slot('route', route('setores.destroy', $setor->id))
										@endcomponent
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>

					</div>
				</div>
			</div>
		</div>

	</div>

@endsection

resources/views/sistema/setores/show.blade.php
@extends('adminlte::page')


@section('content_header')
    <h1>
    	<strong>{{ $setor->nome }}</strong> <small>Lista de materiais cadastrados</small>
    </h1>


    <ol class="breadcrumb">
    	<li>
    		<i class="fa fa-home"></i>
    		<a href="{{ route('home') }}">Home</a>
    	</li>
    	<li>
            <i class="fa fa-building"></i>
            <a href="{{ route('setores.index') }}">Setores
            </a>
    	</li>
        <li class="active">
            <i class="fa fa-list"></i> Lista de materiais
        </li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">

            @if($setor->materiais->isNotEmpty())
                <div class="box box-success">
                    <div class="box-header">
                        <h1 class="box-title">
                            <i class="fa fa-list"></i> Lista de Materiais
                        </h1>

                        <div class="box-tools pull-right">
                            <span class="label label-default">{{ $setor->materiais->count() }} itens cadastrados</span>
                        </div>
                    </div>

                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>Tombamento</th>
                                        <th>Responsável</th>
                                        <th>Valor</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach($setor->materiais as $material)
                                        <tr>
                                            <td>{{ $material->nome }}</td>
                                            <td>{{ $material->tombamento }}</td>
                                            <td>{{ $material->responsavel->nome }}</td>
                                            <td>R$ {{ $material->valor }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                
                            </table>
                        </div>
                        
                    </div>

                    <div class="box-footer">
                        <h4>
                            <div class="pull-left">
                                <strong>Total:</strong>
                                R$ {{ number_format($setor->materiais->sum('valor'), 2, ',','.') }}
                            </div>
                        </h4>
                    </div>
                    
                </div>
            @else
                <div class="well ">
                    <i class="fa fa-info-circle"></i> Nenhum material encontrado.
                </div>
            @endif

        </div>

        <div class="col-lg-12">
            <a href={{ route('setores.index') }}  class="btn btn-default pull-left">
                Voltar
            </a>
        </div>
    </div>

@stop